### ISSUE TITLE
About  pre-processing and post-processing

### ISSUE THREAD

**Issue by Joker-ZXR** [RaphaelScho/Predicting-deliverable-treatment-plans#1]
Hello, I read your papers "Deep Learning based Prediction of Deliverable Treatment Plans in Radiation Oncology" and "Generating deliverable DICOM RT treatment plans for prostate VMAT by predicting MLC motion sequences with an encoder-decoder network" and found these really interesting ideas.
But how did you achieve the pre-processing and post-processing of the data? I see that the code comes from a private repo, and I cannot view it.  Could you make the code public now? Thanks!

**Comment by RaphaelScho** [comment]
All code for "Deep Learning based Prediction of Deliverable Treatment Plans in Radiation Oncology" is publicly available right here in this repository. The preprocessing code is under [Preprocessing](https://github.com/RaphaelScho/Predicting-deliverable-treatment-plans/tree/main/Preprocessing) and postprocessing under [Postprocessing](https://github.com/RaphaelScho/Predicting-deliverable-treatment-plans/tree/main/Postprocessing) for video creation and [dosimetric_eval](https://github.com/RaphaelScho/Predicting-deliverable-treatment-plans/tree/main/Other/dosimetric_eval) for plan creation and plotting.

Some information about each file and their uses can be found in [structure.txt](https://github.com/RaphaelScho/Predicting-deliverable-treatment-plans/blob/main/structure.txt).

For "Generating deliverable DICOM RT treatment plans for prostate VMAT by predicting MLC motion sequences with an encoder-decoder network" please contact the other authors.
